---

general_settings:
  store_model_in_db: true

database_settings:
  database_url: "postgresql://litellm:litellm@postgres:5432/litellm"

model_list:

  - model_name: "tinyllama-1.1b-chat"
    litellm_params:
      custom_llm_provider: "openai"
      model: "openai/TinyLlama/TinyLlama-1.1B-Chat-v1.0"
      api_base: "http://vllm:8000/v1"
      api_key: "os.environ/LOCAL_VLLM_API_KEY"

  - model_name: "ministral-3-8b"
    litellm_params:
      custom_llm_provider: "openai"
      model: "mistralai/Ministral-3-8B-Instruct-2512"
      api_base: "http://vllm:8000/v1"
      api_key: "os.environ/LOCAL_VLLM_API_KEY"

  - model_name: "qwen2.5-3b"
    litellm_params:
      custom_llm_provider: "openai"
      model: "Qwen/Qwen2.5-3B-Instruct"
      api_base: "http://vllm:8000/v1"
      api_key: "os.environ/LOCAL_VLLM_API_KEY"

  - model_name: "gpt-5.4-mini"
    litellm_params:
      model: "openai/gpt-5.4-mini"
      api_key: "os.environ/AZURE_OPENAI_API_KEY"

  - model_name: "gpt-5.4"
    litellm_params:
      model: "openai/gpt-5.4"
      api_key: "os.environ/AZURE_OPENAI_API_KEY"

  - model_name: "gpt-5.5"
    litellm_params:
      model: "openai/gpt-5.5"
      api_key: "os.environ/AZURE_OPENAI_API_KEY"

...
